version: '3.1'

# https://www.tfzx.net/article/2864556.html
# networks:
#     default:
#         driver: bridge
#         ipam:
#             config:
#                 - subnet: 172.177.57.0/24

services:
    php-fpm:
        build:
            context: ./fpm
        image: ricardo/fpm-alpine:latest
        restart: unless-stopped
        container_name: mage-fpm
        user: www-data
        volumes:
            - './magento:/var/www/html/magento'
            - './.composer:/home/www-data/.composer'
            - './.composer/auth.json:/home/www-data/.composer/auth.json'
            - './fpm/99-php-custom.ini:/usr/local/etc/php/conf.d/99-php-custom.ini'
            - '/var/www/.ssh:/home/www-data/.ssh'
        links:
            - db
            - elastics

    web:
        image: nginx:1.20.0-alpine
        container_name: mage-web
        ports:
            - "1918:80"
            - "1919:1919"
        volumes:
            - "./nginx/magento-base.conf:/etc/nginx/conf.d/magento-base.conf"
            - "./magento:/var/www/html/magento"
        depends_on:
            - php-fpm
            - db
        links:
            - php-fpm
            - db

    db:
        image: mysql
        container_name: mage-db
        command: --default-authentication-plugin=mysql_native_password
        # restart: always
        # user: nobody
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # has to be string
        volumes:
            - './mysql-data:/var/lib/mysql'
        # ports:
        #     - 1920:3306
    
    elastics:
        image: docker.io/bitnami/elasticsearch:7
        container_name: mage-elastic
        # ports:
        #     - '9200:9200'
        #     - '9300:9300'

    code-server:
        build:
            context: ../docker-compose-code-server/etc/code-server-dockerfile
        image: ricardo/codeserver-alpine:latest
        container_name: code-server
        environment:
          - BUID=82 #build user id
          - BGID=82
        volumes:
            - ./code-server/.config/config.yaml:/home/coder/.config/code-server/config.yaml
            - ./code-server/code-server:/home/coder/.local/share/code-server
        ports:
            - 7000:8080
        # restart: unless-stopped


# elasticsearch may not run if this is not executed on the docker host: sysctl -w vm.max_map_count=262144

# composer create-project --repository=https://repo.magento.com/ magento/project-community-edition DIRNAME
# bin/magento setup:install --base-url=http://sandbox.flagship.zone:1919 --backend-frontname=admin --db-host=db --db-name=magento --db-user=root --db-password="" --admin-firstname=Magento --admin-lastname=User --admin-email=ricardorg@mailinator.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=CAD --timezone=America/Toronto --search-engine=elasticsearch7 --elasticsearch-host=elastics --elasticsearch-port=9200 --cleanup-database
